# Generated by Django 3.2.7 on 2021-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('blurb', models.CharField(max_length=1000)),
                ('first_line', models.CharField(max_length=250)),
                ('last_line', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
