# Generated by Django 3.2.7 on 2021-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('first_line', models.CharField(max_length=250)),
                ('last_line', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('first_line', models.CharField(max_length=250)),
                ('last_line', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
